name: Format & Lint & Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  dependencies:
    runs-on: ubuntu-latest
    name: Install and cache dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cached-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci

  lint-and-format:
    runs-on: ubuntu-latest
    needs: [dependencies]
    name: Run Format & Lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore cached dependencies
        uses: actions/cache@v2
        env:
          cache-name: cached-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Run prettier ğŸ¦‹
        run: npm run format:check
      - name: Run EsLint âœ…
        run: npm run lint:js
      - name: Run StyleLint âœ…
        run: npm run lint:style

  cypress:
    runs-on: ubuntu-latest
    needs: [dependencies]
    name: Run Cypress
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore cached dependencies
        uses: actions/cache@v2
        env:
          cache-name: cached-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Run Cypress ğŸ–¥ï¸
        uses: cypress-io/github-action@v2
        with:
          start: npm run dev
          wait-on: http://localhost:8080/
  unit:
    runs-on: ubuntu-latest
    needs: [dependencies]
    name: Run Unit tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore cached dependencies
        uses: actions/cache@v2
        env:
          cache-name: cached-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Run Jest ğŸ§ª
        run: npm run test
  build-and-deploy:
    runs-on: ubuntu-latest
    needs: [dependencies]
    name: Run Build and Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore cached dependencies
        uses: actions/cache@v2
        env:
          cache-name: cached-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Run Build ğŸ”¨
        run: npm run build
      - name: Run Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: build
